version: '3.8'
services:
  php-cli:
    build: ./
    volumes:
      - .:/app
    working_dir: /app

  composer:
    image: composer
    volumes:
      - .:/app
      - .:/opt/project
    working_dir: /app
